# Generated by Django 5.0.3 on 2024-04-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="email",
            field=models.EmailField(
                default="",
                max_length=254,
                unique=True,
                verbose_name="email address main",
            ),
        ),
    ]
