# Generated by Django 5.0.3 on 2024-03-28 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=55)),
                ("name", models.CharField(max_length=20)),
                (
                    "phone",
                    models.IntegerField(
                        validators=[
                            django.core.validators.RegexValidator(
                                message="phone number should be in 10 digits",
                                regex="^\\d{12}$",
                            )
                        ]
                    ),
                ),
                ("queries", models.TextField()),
            ],
        ),
    ]
