# Generated by Django 5.0.3 on 2024-03-30 01:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0002_alter_contact_phone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="user",
            field=models.ManyToManyField(max_length=55, to=settings.AUTH_USER_MODEL),
        ),
    ]
